# Generated by Django 5.0.4 on 2024-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_laptop_delete_chessplayer_delete_dungeon_delete_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(default='no title', max_length=100)),
                ('rating', models.PositiveIntegerField(default=1500)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
                ('games_drawn', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
