# Generated by Django 5.0.4 on 2024-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_chessplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=10)),
                ('preparation_time', models.CharField(max_length=30)),
                ('difficulty', models.PositiveIntegerField()),
                ('calories', models.PositiveIntegerField()),
                ('chef', models.CharField(max_length=100)),
            ],
        ),
    ]
