# Generated by Django 5.0.4 on 2024-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('boss_name', models.CharField(max_length=100)),
                ('recommended_level', models.PositiveIntegerField()),
                ('boss_health', models.PositiveIntegerField()),
                ('reward', models.TextField()),
            ],
        ),
    ]
