# Generated by Django 5.0.4 on 2024-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_dungeon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('workout_type', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Yoga', 'Yoga'), ('CrossFit', 'CrossFit'), ('Calisthenics', 'Calisthenics')], max_length=20)),
                ('duration', models.CharField(max_length=30)),
                ('difficulty', models.CharField(max_length=50)),
                ('calories_burned', models.PositiveIntegerField()),
                ('instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
