# Generated by Django 5.0.4 on 2024-08-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_author_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.author'),
        ),
    ]
